{
 "title": "New dashboard",
 "description": "idk",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "P1 — Pressão entrada",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_LAB\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"filtro_agua\")\r\n  |> filter(fn: (r) => r._field == \"p1_kpa\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "ΔP — Pressão diferencial",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_LAB\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"filtro_agua\")\r\n  |> filter(fn: (r) => r._field == \"dp_kpa\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "P2 — Pressão saída",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_LAB\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"filtro_agua\")\r\n  |> filter(fn: (r) => r._field == \"p2_kpa\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Estado do filtro",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_LAB\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"filtro_agua\")\r\n  |> filter(fn: (r) => r._field == \"saturado\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Caudal",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IoT_LAB\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r._measurement == \"filtro_agua\")\r\n  |> filter(fn: (r) => r._field == \"flow_pct\")\r\n  |> last()"
    }
   ]
  }
 ]
}